apiVersion: v1
data:
  mapRoles: |
 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::413396670218:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1K6B5MAN34JKN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::413396670218:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-25T10:27:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "89007"
  uid: e2ea9f23-5996-4c2b-b81c-ec5723ccc8eb
